"""Domain vocabulary for APIx: airports, the city-pair basket, booking windows,
provenance labels and source metadata.

This module is deliberately data-only and dependency-free so it can be imported by
tests, the CLI, the API and the reconstruction engine without cycles.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

# ---------------------------------------------------------------- booking windows
# T is the travel date. T+N means the fare was observed N days BEFORE travel.
# (The PS writes these as T+1 ... T+45; Context-of-PS.md fixes the reading:
#  T+45 = booked 45 days ahead = typically cheapest.)
BOOKING_WINDOWS: tuple[int, ...] = (1, 7, 15, 30, 45)


class Sector(str, Enum):
    RURAL = "Rural"
    URBAN = "Urban"
    COMBINED = "Combined"


class Provenance(str, Enum):
    """How a fare observation came to exist. Never inferred, always recorded.

    LIVE_SCRAPE      -- Playwright read it off a robots-allowed public page.
    OFFICIAL_API     -- Amadeus Self-Service / Duffel returned it under their ToS.
    RECONSTRUCTED    -- generated by the anchored model in apix.pipeline.reconstruct,
                        calibrated on published CPI/DGCA/ATF anchors. NOT a real quote.
    """

    LIVE_SCRAPE = "LIVE_SCRAPE"
    OFFICIAL_API = "OFFICIAL_API"
    RECONSTRUCTED = "RECONSTRUCTED"

    @property
    def is_observed(self) -> bool:
        return self in (Provenance.LIVE_SCRAPE, Provenance.OFFICIAL_API)


class Availability(str, Enum):
    AVAILABLE = "available"
    SOLD_OUT = "sold_out"
    CANCELLED = "cancelled"
    NO_SERVICE = "no_service"
    FETCH_FAILED = "fetch_failed"
    BLOCKED_BY_ROBOTS = "blocked_by_robots"


class SourceType(str, Enum):
    AIRLINE = "airline"
    OTA = "ota"
    OFFICIAL_API = "official_api"


class ComplianceVerdict(str, Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"  # official APIs: governed by ToS, not robots.txt


@dataclass(frozen=True)
class Airport:
    iata: str
    city: str
    name: str
    state: str
    state_code: int  # MoSPI state_code, lets us join to state-level CPI
    lat: float
    lon: float


AIRPORTS: dict[str, Airport] = {
    a.iata: a
    for a in [
        Airport("DEL", "Delhi", "Indira Gandhi International", "NCT of Delhi", 25, 28.5562, 77.1000),
        Airport("BOM", "Mumbai", "Chhatrapati Shivaji Maharaj Intl", "Maharashtra", 18, 19.0896, 72.8656),
        Airport("BLR", "Bengaluru", "Kempegowda International", "Karnataka", 13, 13.1986, 77.7066),
        Airport("CCU", "Kolkata", "Netaji Subhas Chandra Bose Intl", "West Bengal", 33, 22.6547, 88.4467),
        Airport("HYD", "Hyderabad", "Rajiv Gandhi International", "Telangana", 36, 17.2403, 78.4294),
        Airport("MAA", "Chennai", "Chennai International", "Tamil Nadu", 30, 12.9941, 80.1709),
        Airport("PNQ", "Pune", "Pune Airport", "Maharashtra", 18, 18.5822, 73.9197),
        Airport("AMD", "Ahmedabad", "Sardar Vallabhbhai Patel Intl", "Gujarat", 8, 23.0772, 72.6347),
        Airport("GOI", "Goa", "Manohar International (Mopa)", "Goa", 7, 15.7440, 73.8580),
        Airport("COK", "Kochi", "Cochin International", "Kerala", 14, 10.1520, 76.4019),
        Airport("LKO", "Lucknow", "Chaudhary Charan Singh Intl", "Uttar Pradesh", 31, 26.7606, 80.8893),
        Airport("JAI", "Jaipur", "Jaipur International", "Rajasthan", 29, 26.8242, 75.8122),
        Airport("PAT", "Patna", "Jay Prakash Narayan", "Bihar", 5, 25.5913, 85.0880),
        Airport("GAU", "Guwahati", "Lokpriya Gopinath Bordoloi Intl", "Assam", 4, 26.1061, 91.5859),
        Airport("SXR", "Srinagar", "Sheikh ul-Alam International", "Jammu and Kashmir", 12, 33.9871, 74.7742),
        Airport("IXC", "Chandigarh", "Shaheed Bhagat Singh Intl", "Chandigarh", 6, 30.6735, 76.7885),
    ]
}


@dataclass(frozen=True)
class Route:
    origin: str
    destination: str
    tier: int  # 1 = PS-named core basket, 2 = high-traffic extension
    notes: str = ""

    @property
    def key(self) -> str:
        return f"{self.origin}-{self.destination}"

    @property
    def label(self) -> str:
        return f"{AIRPORTS[self.origin].city} → {AIRPORTS[self.destination].city}"

    @property
    def unordered_key(self) -> str:
        """Directionless key, for joining to O&D traffic tables that are symmetric."""
        return "-".join(sorted((self.origin, self.destination)))


# The six routes in the PS text are tier 1 and are always collected. Tier 2 widens
# coverage to the busiest remaining domestic O&D pairs so the index is not a toy.
# Both directions are tracked because dynamic pricing is NOT symmetric.
ROUTE_BASKET: tuple[Route, ...] = (
    Route("DEL", "BOM", 1, "Named in PS. Busiest domestic O&D in India."),
    Route("BOM", "DEL", 1, "Named in PS, reverse leg."),
    Route("DEL", "BLR", 1, "Named in PS."),
    Route("BLR", "DEL", 1, "Named in PS, reverse leg."),
    Route("BOM", "BLR", 1, "Named in PS."),
    Route("BLR", "BOM", 1, "Named in PS, reverse leg."),
    Route("DEL", "CCU", 1, "Named in PS."),
    Route("CCU", "DEL", 1, "Named in PS, reverse leg."),
    Route("BLR", "HYD", 1, "Named in PS. Short-haul metro pair."),
    Route("HYD", "BLR", 1, "Named in PS, reverse leg."),
    Route("MAA", "DEL", 1, "Named in PS."),
    Route("DEL", "MAA", 1, "Named in PS, reverse leg."),
    Route("DEL", "HYD", 2, "Top-10 O&D by DGCA domestic traffic."),
    Route("DEL", "PNQ", 2, "Top-10 O&D; business corridor."),
    Route("DEL", "AMD", 2, "High-frequency business corridor."),
    Route("BOM", "GOI", 2, "Strong leisure seasonality — stresses the index."),
    Route("DEL", "GOI", 2, "Leisure + festival surge behaviour."),
    Route("BLR", "MAA", 2, "Dense short-haul South corridor."),
    Route("DEL", "LKO", 2, "Tier-2 city representation."),
    Route("DEL", "SXR", 2, "Seasonal + capacity-constrained; tests outlier logic."),
    Route("BOM", "COK", 2, "West–South leisure/labour corridor."),
    Route("DEL", "JAI", 2, "Very short haul; near-substitutable by rail."),
)

TIER1_ROUTES: tuple[Route, ...] = tuple(r for r in ROUTE_BASKET if r.tier == 1)
ROUTES_BY_KEY: dict[str, Route] = {r.key: r for r in ROUTE_BASKET}


@dataclass(frozen=True)
class SourceSpec:
    """Everything the runtime needs to know about one fare source.

    ``search_path_template`` is the *exact* path whose robots.txt verdict gates this
    adapter. It is not decoration: apix.compliance evaluates this literal path.
    """

    slug: str
    display_name: str
    source_type: SourceType
    base_url: str
    robots_url: str
    search_path_template: str
    carriers: tuple[str, ...] = ()
    tos_url: str = ""
    documented_verdict: ComplianceVerdict = ComplianceVerdict.UNKNOWN
    governing_rule: str = ""
    notes: str = ""
    requires_credentials: tuple[str, ...] = ()
    weight_hint: float = 1.0
    tags: tuple[str, ...] = field(default_factory=tuple)


# ---------------------------------------------------------------------------------
# THE SOURCE REGISTRY
#
# ``documented_verdict`` records what we measured on 2026-08-31 (see
# docs/RESEARCH-FINDINGS.md §2). It is documentation only — the runtime NEVER trusts
# it. Every collection run re-fetches robots.txt and re-decides. If an operator
# changes their policy in either direction, APIx follows within one cache TTL.
# ---------------------------------------------------------------------------------

AIRLINE_SOURCES: tuple[SourceSpec, ...] = (
    SourceSpec(
        slug="akasa",
        display_name="Akasa Air",
        source_type=SourceType.AIRLINE,
        base_url="https://www.akasaair.com",
        robots_url="https://www.akasaair.com/robots.txt",
        search_path_template="/booking/search",
        carriers=("QP",),
        tos_url="https://www.akasaair.com/legal/terms-and-conditions",
        documented_verdict=ComplianceVerdict.ALLOW,
        governing_rule="User-Agent: * group present with no Disallow directive at all",
        notes="Cleanest robots.txt of the eleven. Primary live airline source.",
        weight_hint=1.0,
        tags=("live", "lcc"),
    ),
    SourceSpec(
        slug="spicejet",
        display_name="SpiceJet",
        source_type=SourceType.AIRLINE,
        base_url="https://www.spicejet.com",
        robots_url="https://www.spicejet.com/robots.txt",
        search_path_template="/booking/search",
        carriers=("SG",),
        tos_url="https://www.spicejet.com/conditionsofcarriage",
        documented_verdict=ComplianceVerdict.ALLOW,
        governing_rule="User-agent: * -> 'Disallow:' (empty value = allow everything)",
        notes=(
            "robots.txt contains a malformed absolute-URL Disallow "
            "(https://www.spicejet.com/api/v1). RFC 9309 requires path-relative "
            "patterns, so a strict parser would ignore it. We honour the intent and "
            "treat /api/v1 as denied anyway."
        ),
        weight_hint=1.0,
        tags=("live", "lcc"),
    ),
    SourceSpec(
        slug="airindia",
        display_name="Air India",
        source_type=SourceType.AIRLINE,
        base_url="https://www.airindia.com",
        robots_url="https://www.airindia.com/robots.txt",
        search_path_template="/in/en/booking/flight-search",
        carriers=("AI",),
        tos_url="https://www.airindia.com/in/en/legal/terms-and-conditions.html",
        documented_verdict=ComplianceVerdict.ALLOW,
        governing_rule="Only /bin/, DAM asset paths and google-flight-booking.html denied",
        notes=(
            "Air India publishes named groups for GPTBot, ClaudeBot, PerplexityBot, "
            "Google-Extended and xAI-Bot — all allowed with the same four exclusions. "
            "An operator that thought carefully about automated access."
        ),
        weight_hint=1.4,
        tags=("live", "fsc"),
    ),
    SourceSpec(
        slug="indigo",
        display_name="IndiGo",
        source_type=SourceType.AIRLINE,
        base_url="https://www.goindigo.in",
        robots_url="https://www.goindigo.in/robots.txt",
        search_path_template="/search.html",
        carriers=("6E",),
        tos_url="https://www.goindigo.in/information/conditions-of-carriage.html",
        documented_verdict=ComplianceVerdict.DENY,
        governing_rule="Disallow: /search.html, /booking/*, /book/*, /bookings/*",
        notes=(
            "Doubly out of reach: explicitly disallowed AND defended by Akamai at the "
            "TLS layer (curl completes the handshake, is asked to renegotiate twice, "
            "then stalls with 0 bytes). We report this rather than defeat it. IndiGo "
            "carries ~60% of domestic seats, so its absence is the strongest argument "
            "for the official-API path — see docs/COMPLIANCE.md §5."
        ),
        weight_hint=2.4,
        tags=("gated", "lcc", "bot-defended"),
    ),
    SourceSpec(
        slug="airindiaexpress",
        display_name="Air India Express",
        source_type=SourceType.AIRLINE,
        base_url="https://www.airindiaexpress.com",
        robots_url="https://www.airindiaexpress.com/robots.txt",
        search_path_template="/flight-availability",
        carriers=("IX",),
        tos_url="https://www.airindiaexpress.com/terms-and-conditions",
        documented_verdict=ComplianceVerdict.DENY,
        governing_rule="Disallow: /flight-availability",
        notes="Availability path denied by name. Adapter ships, gate keeps it parked.",
        weight_hint=1.0,
        tags=("gated", "lcc"),
    ),
    SourceSpec(
        slug="vistara",
        display_name="Vistara",
        source_type=SourceType.AIRLINE,
        base_url="https://www.airvistara.com",
        robots_url="https://www.airvistara.com/robots.txt",
        search_path_template="/trip/flight-search",
        carriers=("UK",),
        tos_url="https://www.airvistara.com/in/en/terms-and-conditions",
        documented_verdict=ComplianceVerdict.DENY,
        governing_rule="Disallow: /trip/*",
        notes="Vistara explicitly denies the /trip/ path which governs flight search. Must use reconstructed data.",
        weight_hint=1.2,
        tags=("gated", "fsc"),
    ),
)

OTA_SOURCES: tuple[SourceSpec, ...] = (
    SourceSpec(
        slug="yatra",
        display_name="Yatra",
        source_type=SourceType.OTA,
        base_url="https://www.yatra.com",
        robots_url="https://www.yatra.com/robots.txt",
        search_path_template="/flight-search",
        tos_url="https://www.yatra.com/online-travel-services-agreement",
        documented_verdict=ComplianceVerdict.ALLOW,
        governing_rule="Allow: /; only /flights-india-vx/, /pwa/ and affiliate paths denied",
        notes="The one OTA of the six that permits its fare-search path. Primary live OTA.",
        weight_hint=1.0,
        tags=("live", "ota"),
    ),
    SourceSpec(
        slug="makemytrip",
        display_name="MakeMyTrip",
        source_type=SourceType.OTA,
        base_url="https://www.makemytrip.com",
        robots_url="https://www.makemytrip.com/robots.txt",
        search_path_template="/flight/search",
        tos_url="https://www.makemytrip.com/legal/in/user_agreement",
        documented_verdict=ComplianceVerdict.DENY,
        governing_rule="Disallow: /flight/search*, /flight/fis*, /air/*",
        notes=(
            "Their robots.txt carries a maintainer comment explaining that a crawler "
            "reads only its single most-specific matching group and does not inherit "
            "the '*' group. That is exactly RFC 9309 §2.2.1 and exactly what our "
            "parser implements."
        ),
        weight_hint=1.8,
        tags=("gated", "ota"),
    ),
    SourceSpec(
        slug="easemytrip",
        display_name="EaseMyTrip",
        source_type=SourceType.OTA,
        base_url="https://www.easemytrip.com",
        robots_url="https://www.easemytrip.com/robots.txt",
        search_path_template="/flight-search/listing",
        tos_url="https://www.easemytrip.com/terms-conditions.html",
        documented_verdict=ComplianceVerdict.DENY,
        governing_rule="Disallow: /flight-search/listing*",
        weight_hint=1.0,
        tags=("gated", "ota"),
    ),
    SourceSpec(
        slug="cleartrip",
        display_name="Cleartrip",
        source_type=SourceType.OTA,
        base_url="https://www.cleartrip.com",
        robots_url="https://www.cleartrip.com/robots.txt",
        search_path_template="/flights/search",
        tos_url="https://www.cleartrip.com/terms-of-use",
        documented_verdict=ComplianceVerdict.DENY,
        governing_rule="Disallow: /flights/search* (and the /m/ mobile mirror)",
        weight_hint=1.2,
        tags=("gated", "ota"),
    ),
    SourceSpec(
        slug="ixigo",
        display_name="Ixigo",
        source_type=SourceType.OTA,
        base_url="https://www.ixigo.com",
        robots_url="https://www.ixigo.com/robots.txt",
        search_path_template="/flights/search",
        tos_url="https://www.ixigo.com/about/terms",
        documented_verdict=ComplianceVerdict.DENY,
        governing_rule="Disallow: /flights/search, /api/, /m/",
        weight_hint=1.0,
        tags=("gated", "ota"),
    ),
    SourceSpec(
        slug="goibibo",
        display_name="Goibibo",
        source_type=SourceType.OTA,
        base_url="https://www.goibibo.com",
        robots_url="https://www.goibibo.com/robots.txt",
        search_path_template="/flights/air-DEL-BOM-20260901--1-0-0-E-D/?mode=search",
        tos_url="https://www.goibibo.com/info/terms/",
        documented_verdict=ComplianceVerdict.DENY,
        governing_rule="Disallow: /flights/*?mode=* — every real search URL carries mode",
        notes=(
            "A wildcard-in-query rule. Naive parsers that only compare path prefixes "
            "would score this ALLOW and scrape it. Ours matches the query string, "
            "which is why the verdict is DENY."
        ),
        weight_hint=1.3,
        tags=("gated", "ota"),
    ),
)

OFFICIAL_API_SOURCES: tuple[SourceSpec, ...] = (
    SourceSpec(
        slug="amadeus",
        display_name="Amadeus Self-Service (Flight Offers Search)",
        source_type=SourceType.OFFICIAL_API,
        base_url="https://test.api.amadeus.com",
        robots_url="",
        search_path_template="/v2/shopping/flight-offers",
        tos_url="https://developers.amadeus.com/self-service/apis-docs/terms-of-use",
        documented_verdict=ComplianceVerdict.NOT_APPLICABLE,
        governing_rule="Governed by the Amadeus Self-Service ToS, not robots.txt",
        notes=(
            "GDS-sourced published fares across most carriers, including the ones whose "
            "own sites are gated. This is the production-correct route for a government "
            "statistical system and it is why the compliance gate costs us little."
        ),
        requires_credentials=("APIX_AMADEUS_CLIENT_ID", "APIX_AMADEUS_CLIENT_SECRET"),
        weight_hint=2.0,
        tags=("official", "api", "multi-carrier"),
    ),
    SourceSpec(
        slug="duffel",
        display_name="Duffel Flights API",
        source_type=SourceType.OFFICIAL_API,
        base_url="https://api.duffel.com",
        robots_url="",
        search_path_template="/air/offer_requests",
        tos_url="https://duffel.com/legal/terms",
        documented_verdict=ComplianceVerdict.NOT_APPLICABLE,
        governing_rule="Governed by the Duffel API terms; test-mode tokens are free",
        notes="Second independent official feed — gives us cross-source corroboration "
        "for the surge-vs-data-error classifier without touching a gated site.",
        requires_credentials=("APIX_DUFFEL_ACCESS_TOKEN",),
        weight_hint=1.5,
        tags=("official", "api", "multi-carrier"),
    ),
)

SOURCES: tuple[SourceSpec, ...] = AIRLINE_SOURCES + OTA_SOURCES + OFFICIAL_API_SOURCES
SOURCES_BY_SLUG: dict[str, SourceSpec] = {s.slug: s for s in SOURCES}

# The eleven the PS names, in PS order — used by docs and the compliance matrix UI.
PS_ELEVEN: tuple[str, ...] = (
    "indigo",
    "airindia",
    "airindiaexpress",
    "akasa",
    "spicejet",
    "makemytrip",
    "yatra",
    "easemytrip",
    "cleartrip",
    "ixigo",
    "goibibo",
)


def expected_observations_per_day(
    n_routes: int | None = None, n_sources: int | None = None
) -> int:
    """Denominator of the confidence score: routes x windows x enabled sources."""
    n_routes = len(ROUTE_BASKET) if n_routes is None else n_routes
    n_sources = len(SOURCES) if n_sources is None else n_sources
    return n_routes * len(BOOKING_WINDOWS) * n_sources



